{% set name = "fluidsim-core" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fluidsim-core-{{ version }}.tar.gz
  sha256: 7edc043c971d90ede1ff85928743e6fb5bcbf600db632fd9a0ec4eb4384905e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - entrypoints
    - fluiddyn >=0.3.2
    - python >=3.8

test:
  imports:
    - fluidsim_core
    - fluidsim_core.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://foss.heptapod.net/fluiddyn/fluidsim
  summary: Pure-Python core library for FluidSim framework
  license: LicenseRef-CeCILL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
    - ashwinvis
